spring:
    h2:
      console:
        enabled: true
        path: /h2
    datasource:
      driverClassName: org.postgresql.Driver
      url: ${DATASOURCE_URL}
      username: postgres
      password: password
    jpa:
      hibernate.ddl-auto: create-drop
      generate-ddl: true
      show-sql: true
      defer-datasource-initialization: true
    ai:
      ollama:
        chat:
          options:
            model: llama3

emailTest: 'user@example.com'
passwordTest: '@Password1k+'
