spring:
  config:
    import: optional:secrets.properties
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: postgres
    password: password
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  ai:
    ollama:
      chat:
        options:
          model: llama3
