spring:
  application:
    name: deep

  #postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/deep
    username: wendel
    password: deep
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect