spring:
  application:
    name: deep
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:


emailTest: 'user@example.com'
passwordTest: '@Password1k+'
