spring:
    h2:
      console:
        enabled: true
        path: /h2-console
    datasource:
      url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
      username: sa
      password:
    jpa:
      hibernate.ddl-auto: create-drop
      generate-ddl: true
      show-sql: true
      defer-datasource-initialization: true
    ai:
      ollama:
        chat:
          options:
            model: llama3

security:
  token:
    private-key: 'classpath:app.key'
    public-key: 'classpath:app.pub'
    expiration-token: 15
    expiration-refresh-token: 30

initiation:
  admin:
    password: '@Admin23k+'
  user:
    password: '@User23k+'

emailTest: 'user@example.com'
passwordTest: '@Password1k+'

deep:
  openapi:
    dev-url: http://localhost:8080
    prod-url: https://www.orgatri.com