spring:
  application:
    name: deep

  datasource:
    url: jdbc:mysql://localhost:3306/teste?useSSL=false&serverTimezone=UTC
    username: root
    password: nicolly
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

